---

- hosts: server

  tasks:
    - name: create a new database for WordPress
      mysql_db:
        login_user: root
        login_password: 123password123
        name: wordpress
        state: present
        encoding: utf8

    - name: create a new user and assgin SELECT permission to the user
      mysql_user:
        login_user: root
        login_password: 123password123
        name: wpuser
        password: 123password123
        host: 'localhost'
        priv: 'wordpress.*:ALL,GRANT'
        state: present

    - name: restart mysql
      service:
        name: mysql
        state: restarted

    - name: config Nginx
      template:
          src: templates/default
          dest: /etc/nginx/sites-available/

    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: install PHP Extensions
      action: >
        {{ ansible_pkg_mgr }} name={{ item }} state=present 
      with_items:
        - php-curl 
        - php-gd 
        - php-mbstring 
        - php-mcrypt 
        - php-xml 
        - php-xmlrpc

    - name: restart php7.0-fpm
      service:
        name: php7.0-fpm
        state: restarted

    - name: download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/

    - name: Extract WordPress
      unarchive:
        src: /tmp/latest.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Extract the compressed file
      shell: tar xzvf /tmp/latest.tar.gz

    - name: copy sample config file
      command: cp /tmp/wordpress/wp-config-sample.php /tmp/wordpress/wp-config.php

    - name: create the upgrade directory
      file: path=/tmp/wordpress/wp-content/upgrade state=directory  

    - name: copy entire WordPress to nginx document root
      command: cp -a /tmp/wordpress/. /var/www/html

    - name: set database and password for wordpress to access database 
      template:
        src: templates/wp-config.php
        dest: /var/www/html/

